// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vivigest_backend.Infrastructure.Persistance;

#nullable disable

namespace Vivigest_backend.Migrations
{
    [DbContext(typeof(VivigestDbContext))]
    [Migration("20260314215530_DatabaseV1")]
    partial class DatabaseV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.AuthorizedPerson", b =>
                {
                    b.Property<int>("IdAuthorized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuthorized"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<int>("IdRelationshipType")
                        .HasColumnType("int");

                    b.Property<int>("IdResidentUser")
                        .HasColumnType("int");

                    b.Property<int>("IdState")
                        .HasColumnType("int");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAuthorized");

                    b.HasIndex("IdPerson");

                    b.HasIndex("IdRelationshipType");

                    b.HasIndex("IdResidentUser");

                    b.HasIndex("IdState");

                    b.ToTable("AuthorizedPersons");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Complex", b =>
                {
                    b.Property<int>("IdComplex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComplex"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameComplex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdComplex");

                    b.ToTable("Complexes");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Correspondence", b =>
                {
                    b.Property<int>("IdCorrespondence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCorrespondence"));

                    b.Property<DateTime?>("DateDelivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateNotified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReceipt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveredTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCorrespondenceState")
                        .HasColumnType("int");

                    b.Property<int>("IdCorrespondenceType")
                        .HasColumnType("int");

                    b.Property<int>("IdRegisteredBy")
                        .HasColumnType("int");

                    b.Property<int>("IdUnit")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCorrespondence");

                    b.HasIndex("IdCorrespondenceState");

                    b.HasIndex("IdCorrespondenceType");

                    b.HasIndex("IdRegisteredBy");

                    b.HasIndex("IdUnit");

                    b.ToTable("Correspondences");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.CorrespondenceState", b =>
                {
                    b.Property<int>("IdCorrespondenceState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCorrespondenceState"));

                    b.Property<string>("NameCorrespondenceState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCorrespondenceState");

                    b.ToTable("CorrespondenceStates");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.CorrespondenceType", b =>
                {
                    b.Property<int>("IdCorrespondenceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCorrespondenceType"));

                    b.Property<string>("NameCorrespondenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCorrespondenceType");

                    b.ToTable("CorrespondenceTypes");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.DocumentType", b =>
                {
                    b.Property<int>("IdDocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumentType"));

                    b.Property<string>("NameDocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDocumentType");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Incident", b =>
                {
                    b.Property<int>("IdIncident")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncident"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdIncidentType")
                        .HasColumnType("int");

                    b.Property<int>("IdUserReportee")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlEvidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIncident");

                    b.HasIndex("IdIncidentType");

                    b.HasIndex("IdUserReportee");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.IncidentType", b =>
                {
                    b.Property<int>("IdIncidentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncidentType"));

                    b.Property<string>("NameIncidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIncidentType");

                    b.ToTable("IncidentTypes");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("IdPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPayment"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("IdPaymentPeriod")
                        .HasColumnType("int");

                    b.Property<int>("IdRegisterdBy")
                        .HasColumnType("int");

                    b.Property<int>("IdUnit")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPayment");

                    b.HasIndex("IdPaymentMethod");

                    b.HasIndex("IdPaymentPeriod");

                    b.HasIndex("IdRegisterdBy");

                    b.HasIndex("IdUnit");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("IdPaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaymentMethod"));

                    b.Property<string>("NameMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPaymentMethod");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.PaymentPeriod", b =>
                {
                    b.Property<int>("IdPaymentPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaymentPeriod"));

                    b.Property<string>("NamePeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPaymentPeriod");

                    b.ToTable("PaymentPeriods");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerson"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDocumentType")
                        .HasColumnType("int");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerson");

                    b.HasIndex("IdDocumentType");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.RelationshipType", b =>
                {
                    b.Property<int>("IdRelationshipType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRelationshipType"));

                    b.Property<string>("NameRelationshipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRelationshipType");

                    b.ToTable("RelationshipTypes");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Residence", b =>
                {
                    b.Property<int>("IdResidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResidence"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUnit")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdResidence");

                    b.HasIndex("IdUnit");

                    b.HasIndex("IdUser");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NameRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.State", b =>
                {
                    b.Property<int>("IdState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdState"));

                    b.Property<string>("NameState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdState");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Tower", b =>
                {
                    b.Property<int>("IdTower")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTower"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdComplex")
                        .HasColumnType("int");

                    b.Property<string>("NameTower")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTower");

                    b.HasIndex("IdComplex");

                    b.ToTable("Towers");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("IdUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnit"));

                    b.Property<decimal>("AreaM2Unit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodeUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FloorUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdState")
                        .HasColumnType("int");

                    b.Property<int>("IdTower")
                        .HasColumnType("int");

                    b.HasKey("IdUnit");

                    b.HasIndex("IdState");

                    b.HasIndex("IdTower");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<bool>("Activated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdPerson")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.UserRol", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUser", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Visit", b =>
                {
                    b.Property<int>("IdVisit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVisit"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUnit")
                        .HasColumnType("int");

                    b.Property<int>("IdUserRegister")
                        .HasColumnType("int");

                    b.Property<int>("IdVisitor")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVisit");

                    b.HasIndex("IdUnit");

                    b.HasIndex("IdUserRegister");

                    b.HasIndex("IdVisitor");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Visitor", b =>
                {
                    b.Property<int>("IdVisitor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVisitor"));

                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.HasKey("IdVisitor");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.AuthorizedPerson", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.RelationshipType", "RelationshipType")
                        .WithMany()
                        .HasForeignKey("IdRelationshipType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.User", "ResidentUser")
                        .WithMany()
                        .HasForeignKey("IdResidentUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("IdState")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("RelationshipType");

                    b.Navigation("ResidentUser");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Correspondence", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.CorrespondenceState", "CorrespondenceState")
                        .WithMany()
                        .HasForeignKey("IdCorrespondenceState")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.CorrespondenceType", "CorrespondenceType")
                        .WithMany()
                        .HasForeignKey("IdCorrespondenceType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdRegisteredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("IdUnit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorrespondenceState");

                    b.Navigation("CorrespondenceType");

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Incident", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.IncidentType", "IncidentType")
                        .WithMany()
                        .HasForeignKey("IdIncidentType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.User", "UserReportee")
                        .WithMany()
                        .HasForeignKey("IdUserReportee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncidentType");

                    b.Navigation("UserReportee");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("IdPaymentMethod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.PaymentPeriod", "PaymentPeriod")
                        .WithMany()
                        .HasForeignKey("IdPaymentPeriod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.User", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("IdRegisterdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("IdUnit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentPeriod");

                    b.Navigation("RegisteredBy");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Person", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("IdDocumentType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Residence", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("IdUnit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Tower", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.Complex", "Complex")
                        .WithMany()
                        .HasForeignKey("IdComplex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Unit", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("IdState")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.Tower", "Tower")
                        .WithMany()
                        .HasForeignKey("IdTower")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");

                    b.Navigation("Tower");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.User", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("Vivigest_backend.Domain.Entities.User", "IdPerson")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.UserRol", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.User", "User")
                        .WithMany("UserRols")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.Visit", b =>
                {
                    b.HasOne("Vivigest_backend.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("IdUnit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUserRegister")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivigest_backend.Domain.Entities.Visitor", "Visitor")
                        .WithMany()
                        .HasForeignKey("IdVisitor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("User");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("Vivigest_backend.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRols");
                });
#pragma warning restore 612, 618
        }
    }
}
